apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-simulation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: credit-simulation
  template:
    metadata:
      labels:
        app: credit-simulation
    spec:
      containers:
      - name: credit-simulation
        image: credit-simulation:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: credit-simulation-service
spec:
  selector:
    app: credit-simulation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
