apiVersion: v1
kind: Service
metadata:
  name: credit-simulation-service
spec:
  selector:
    app: credit-simulation
  ports:
    - protocol: TCP
      port: 80         # Porta exposta externamente
      targetPort: 3000 # Porta interna do container
  type: LoadBalancer  # Expõe a aplicação externamente
